# Generated by Django 5.0.7 on 2024-07-24 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('turma_escola', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.FloatField(default=0)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('status', models.FloatField(default=0)),
                ('chave_pix', models.CharField(max_length=32)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo_responsavel', models.CharField(choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('avó', 'Avó'), ('avô', 'Avô'), ('tio', 'Tio'), ('tia', 'Tia'), ('out', 'Outro')], max_length=3, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=30, null=True)),
                ('boleto', models.FloatField(default=0)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=50)),
                ('modalidade', models.CharField(choices=[('j', 'Judô'), ('b', 'Ballet'), ('f', 'Futsal'), ('x', 'Xadrez')], max_length=1)),
                ('escola', models.CharField(choices=[('Externato', 'Externato São José'), ('Santo', 'Santo Agostinho')], max_length=9)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('status', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pagamento', models.CharField(choices=[('men', 'Mensalidade'), ('mat', 'Matrícula'), ('cam', 'Camiseta'), ('col', 'Colant'), ('kim', 'Kimono'), ('eve', 'Evento'), ('out', 'Outro')], max_length=3)),
                ('status', models.FloatField(default=0)),
                ('mes', models.CharField(choices=[('jan', 'Janeiro'), ('fev', 'Fevereiro'), ('mar', 'Março'), ('abr', 'Abril'), ('mai', 'Maio'), ('jun', 'Junho'), ('jul', 'Julho'), ('ago', 'Agosto'), ('set', 'Setembro'), ('out', 'Outubro'), ('nov', 'Novembro'), ('dez', 'Dezembro')], max_length=3)),
                ('ano', models.CharField(choices=[('24', '2024')], max_length=2)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes')),
                ('obs', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca_Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.FloatField(default=0)),
                ('data', models.DateField()),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.funcionarios')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Faltas_Justificadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(blank=True, null=True, upload_to='atestado')),
                ('atestado', models.FloatField(default=0)),
                ('obs', models.TextField()),
                ('presenca_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.presenca_funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel_Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.aluno')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca_Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.FloatField(default=0)),
                ('data', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.aluno')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno_Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('divisão_pagamento', models.CharField(choices=[('men', 'Mensal'), ('anu', 'Anual'), ('sem', 'Semestral'), ('out', 'Outro')], max_length=3)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Turma_Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('seg', 'Segunda-Feira'), ('ter', 'Terça-Feira'), ('qua', 'Quarta-Feira'), ('qui', 'Quinta-Feira'), ('sex', 'Sexta-Feira')], max_length=3)),
                ('valor_aula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.funcionarios')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.turma')),
            ],
        ),
    ]
