# Generated by Django 5.0.7 on 2024-07-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno_turma',
            name='divisão_pagamento',
            field=models.CharField(choices=[('men', 'Mensal'), ('anu', 'Anual'), ('sem', 'Semestral'), ('out', 'Outro')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='aluno_turma',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
