# Generated by Django 5.0.7 on 2024-07-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_funcionarios_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='e_mail',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
