# Generated by Django 5.0.7 on 2024-07-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_responsavel_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
