# Generated by Django 5.0.7 on 2024-10-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_faturamento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='status',
        ),
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
