# Generated by Django 5.0.7 on 2024-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_aluno_status_aluno_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca_aluno',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='presenca_funcionario',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
