# Generated by Django 5.0.7 on 2024-11-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_presenca_aluno_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltas_justificadas',
            name='atestado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='boleto',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='turma',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
