# Generated by Django 5.0.7 on 2024-11-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_faltas_justificadas_atestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='tipo_responsavel',
            field=models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('avó', 'Avó'), ('avô', 'Avô'), ('tio', 'Tio'), ('tia', 'Tia'), ('out', 'Outro')], max_length=3, null=True),
        ),
    ]
