# Generated by Django 5.0.7 on 2024-11-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_responsavel_tipo_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='estendido',
            field=models.BooleanField(default=0),
        ),
    ]
