# Generated by Django 5.0.7 on 2024-11-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_turma_estendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='ano',
            field=models.CharField(choices=[('24', '2024'), ('25', '2025')], max_length=2),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='turma',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
