# Generated by Django 5.0.7 on 2025-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_aluno_ativo_alter_faturamento_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='escola',
            field=models.CharField(choices=[('Casa', 'Casa de Vó'), ('Externato', 'Externato São José'), ('Santo', 'Santo Agostinho')], max_length=9),
        ),
    ]
