# Generated by Django 5.0.7 on 2025-09-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_alter_turma_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('escola', 'Escola'), ('clube', 'Clube'), ('condominio', 'Condomínio'), ('empresa', 'Empresa'), ('outro', 'Outro')], default='escola', max_length=10)),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('contrato', models.FileField(blank=True, null=True, upload_to='parceiros/contratos/')),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='faturamento',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='faturamento',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='faturamento',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='escola',
        ),
        migrations.AddField(
            model_name='faturamento',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('responsavel_contato', models.ForeignKey(blank=True, help_text='Responsável pela comunicação do dia a dia (avisos, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_contato', to='cadastros.responsavel')),
                ('responsavel_financeiro', models.ForeignKey(blank=True, help_text='Responsável pela assinatura de contrato e pagamentos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_financeiro', to='cadastros.responsavel')),
            ],
            options={
                'verbose_name': 'Família',
                'verbose_name_plural': 'Famílias',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='cadastros.familia'),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturamentos', to='cadastros.familia'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='cadastros.familia'),
        ),
        migrations.AddField(
            model_name='turma',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='cadastros.parceiro'),
        ),
    ]
