# Generated by Django 5.0.7 on 2025-09-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_parceiro_remove_faturamento_aluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='nome',
        ),
    ]
