# Generated by Django 5.0.7 on 2025-09-23 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_remove_familia_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faturamento',
            old_name='status',
            new_name='pago',
        ),
        migrations.RemoveField(
            model_name='faturamento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='faturamento',
            name='valor',
        ),
        migrations.AddField(
            model_name='faturamento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='data_vencimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faturamento',
            name='mes_referencia',
            field=models.DateField(default=django.utils.timezone.now, help_text='Primeiro dia do mês de referência da cobrança.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faturamento',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='valor_previsto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor original ou editado com desconto.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastos',
            name='categoria',
            field=models.CharField(choices=[('funcionario', 'Pagamento de Funcionário'), ('uniforme', 'Compra de Uniforme/Material'), ('imposto', 'Impostos'), ('contabilidade', 'Serviços (Contabilidade, etc)'), ('banco', 'Taxas Bancárias'), ('outro', 'Outro')], default='outro', max_length=15),
        ),
        migrations.AddField(
            model_name='gastos',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturamentos', to='cadastros.familia'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('par', 'Parcela da Atividade'), ('mat', 'Matrícula'), ('cam', 'Camiseta'), ('col', 'Colant'), ('kim', 'Kimono'), ('eve', 'Evento'), ('out', 'Outro')], max_length=3),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.funcionarios'),
        ),
    ]
