# Generated by Django 5.0.7 on 2025-10-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Um nome curto para identificar o texto na lista. Ex: Lembrete Amigável', max_length=100, unique=True)),
                ('template', models.TextField(help_text='O conteúdo do texto. Para cobranças, use {nome} para o primeiro nome e {valor} para o valor.')),
            ],
            options={
                'verbose_name': 'Texto',
                'verbose_name_plural': 'Textos',
                'ordering': ['titulo'],
            },
        ),
    ]
